### ISSUE TITLE
IMa2p says infinite sites data is not infinite sites data...

### ISSUE THREAD

**Issue by jfmclaughlin92** [arunsethuraman/ima2p#1]
I'm using IMa2p on ultra-conserved elements data. I set up three runs- two with 20 randomly-selected loci and one with 200 (I was checking how the run times would scale on our HPC system). The first run of 20 ran successfully, but the second of 20 and the 200 both crashed, giving the following error message:

Data not compatible with infinite sites model
seq 59: 0000
seq 12: 0110
seq 13: 1000
seq 25: 1101
IMa2: data not compatible with infinite sites model - locus #: 5, name: uce-4808,  sequence#: 25

...repeated multiple times. 
The infinite sites model is indeed the one I need to be using, so I'm unsure why I'm getting this error. The only thing I can think of is that some of my loci have more variable sites than others, so if most of my loci have few variable sites and then there's one with a lot, it breaks the model parameters. Is there any way to solve this?

I can provide my input file or other files if needed.

Thanks!

**Comment by arunsethuraman** [comment]
Hi Jessica,

The infinite sites model assumes one polymorphism per site. So this
assumption can be easily broken if you have some site with > 1 SNP, a
pattern that can easily be generated by recombination. So to ensure that
your data indeed fits an IS model, you will have to run your loci through
some tool to obtain the longest non-recombining segment, before running
IMa2p on it. Lots of software let you do this - SITES (another tool from
our lab -https://bio.cst.temple.edu/~hey/software/software.htm#SITES), IMGC
- http://hammerlab.biosci.arizona.edu/imgc_online.html, DNAsp, etc.
  Basically run your loci through a 4 gamete test, or some test of
  recombination, then pull out the longest non-recombining segment, then run
  it through IMa2p.

Hope this helps!
Cheers,
Arun

On Fri, Nov 13, 2015 at 3:34 PM, Jessica McLaughlin <
notifications@github.com> wrote:

> I'm using IMa2p on ultra-conserved elements data. I set up three runs- two
> with 20 randomly-selected loci and one with 200 (I was checking how the run
> times would scale on our HPC system). The first run of 20 ran successfully,
> but the second of 20 and the 200 both crashed, giving the following error
> message:
> 
> Data not compatible with infinite sites model
> seq 59: 0000
> seq 12: 0110
> seq 13: 1000
> seq 25: 1101
> IMa2: data not compatible with infinite sites model - locus #: 5, name:
> uce-4808, sequence#: 25
> 
> ...repeated multiple times.
> The infinite sites model is indeed the one I need to be using, so I'm
> unsure why I'm getting this error. The only thing I can think of is that
> some of my loci have more variable sites than others, so if most of my loci
> have few variable sites and then there's one with a lot, it breaks the
> model parameters. Is there any way to solve this?
> 
> I can provide my input file or other files if needed.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunsethuraman/ima2p/issues/1.

## 

Arun Sethuraman, Ph.D.
Postdoctoral Associate
Center for Computational Genetics and Genomics,
Department of Biology
Temple University
1900 N 12th Street
Philadelphia, PA 19122
https://sites.google.com/site/arunsethuraman1/

**Comment by arunsethuraman** [comment]
Just following up - did this fix work for you, Jessica?

**Comment by jfmclaughlin92** [comment]
Yes, we used IMgc and that seems to have worked. Thanks!
