### ISSUE TITLE
IMa2p crashed- floating point exception

### ISSUE THREAD

**Issue by jfmclaughlin92** [arunsethuraman/ima2p#2]
So, I've been doing multiple runs with no problems. I was running a few different sets of loci, and one of them crashed after 47 minutes. I resubmitted to see if it was an issue with the computer, and it crashed again after 47 minutes. This is the error message I get when it begins to print the burn trend file:

```
[n38:39075] Signal: Floating point exception (8)
[n38:39075] Signal code: Integer divide-by-zero (1)
[n38:39075] Failing at address: 0x43cabb
[n38:39075] [ 0] /lib64/libpthread.so.0(+0xf710) [0x2ae50f29b710]
[n38:39075] [ 1] IMa2p() [0x43cabb]
[n38:39075] [ 2] IMa2p() [0x4373bb]
[n38:39075] [ 3] IMa2p() [0x43775d]
[n38:39075] [ 4] IMa2p(main+0x24b) [0x43d12b]
[n38:39075] [ 5] /lib64/libc.so.6(__libc_start_main+0xfd) [0x2ae50f4c7d5d]
[n38:39075] [ 6] IMa2p() [0x40fb99]
[n38:39075] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 39075 on node n38 exited on signal 8 (Floating point exception).
--------------------------------------------------------------------------
```

It then lists all my loci again, followed by:

```
IMa2: problem finding .ti file(s) -   no genealogies loaded from .ti file(s)
  Number of files loaded : 0  total number of genealogies used: 0 out of a total of: 0 
[n38:54475] [[13911,0],0]-[[13911,1],0] mca_oob_tcp_msg_recv: readv failed: Connection reset by peer (104)
--------------------------------------------------------------------------
mpirun has exited due to process rank 0 with PID 54513 on
node n38 exiting without calling "finalize". This may
have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
```

Is this an input file issue? If so, what type, and how can I fix it? 

Thanks!
Jessica

**Comment by arunsethuraman** [comment]
Hi Jessica,

Can you email me (arun@temple.edu) your IMa2p command line? It might also
help if you can send me a sample input file, and the burntrend file.

From the looks of it, you are doing an L mode run using saved genealogies?
Or restarting an M mode run?

Thanks,
Arun

On Thu, Dec 3, 2015 at 3:00 PM, Jessica McLaughlin <notifications@github.com

> wrote:
> 
> So, I've been doing multiple runs with no problems. I was running a few
> different sets of loci, and one of them crashed after 47 minutes. I
> resubmitted to see if it was an issue with the computer, and it crashed
> again after 47 minutes. This is the error message I get when it begins to
> print the burn trend file:
> 
> [n38:39075] Signal: Floating point exception (8)
> [n38:39075] Signal code: Integer divide-by-zero (1)
> [n38:39075] Failing at address: 0x43cabb
> [n38:39075] [ 0] /lib64/libpthread.so.0(+0xf710) [0x2ae50f29b710]
> [n38:39075] [ 1] IMa2p() [0x43cabb]
> [n38:39075] [ 2] IMa2p() [0x4373bb]
> [n38:39075] [ 3] IMa2p() [0x43775d]
> [n38:39075] [ 4] IMa2p(main+0x24b) [0x43d12b]
> [n38:39075] [ 5] /lib64/libc.so.6(__libc_start_main+0xfd) [0x2ae50f4c7d5d]
> [n38:39075] [ 6] IMa2p() [0x40fb99]
> 
> ## [n38:39075] **\* End of error message ***
> 
> ## mpirun noticed that process rank 0 with PID 39075 on node n38 exited on signal 8 (Floating point exception).
> 
> It then lists all my loci again, followed by:
> 
> IMa2: problem finding .ti file(s) -   no genealogies loaded from .ti file(s)
>   Number of files loaded : 0  total number of genealogies used: 0 out of a total of: 0
> 
> ## [n38:54475] [[13911,0],0]-[[13911,1],0] mca_oob_tcp_msg_recv: readv failed: Connection reset by peer (104)
> 
> mpirun has exited due to process rank 0 with PID 54513 on
> node n38 exiting without calling "finalize". This may
> have caused other processes in the application to be
> 
> ## terminated by signals sent by mpirun (as reported here).
> 
> Is this an input file issue? If so, what type, and how can I fix it?
> 
> Thanks!
> Jessica
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunsethuraman/ima2p/issues/2.

## 

Arun Sethuraman, Ph.D.
Postdoctoral Associate/Scientific Programmer
Center for Computational Genetics and Genomics,
Department of Biology
Temple University
1900 N 12th Street
Philadelphia, PA 19122
https://sites.google.com/site/arunsethuraman1/
